version: '3.4'

services:
  thetechblog:
    image: thetechblog
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 10000:10000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
