version: '3.4'

services:
  thetechblog:
    image: thetechblog
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 10000:10000
